auto:        true
server:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   /:year/:month/:day/:title.html
maruku:
    use_tex:   false
    use_divs:  false
    png_dir:   images/latex
    png_url:   /images/latex
